from django.urls import path
from . import views

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("reports/", views.ReportsView.as_view(), name="reports"),
    path("farms/", views.FarmListView.as_view(), name="farm-list"),
    path("farms/add/", views.FarmCreateView.as_view(), name="farm-add"),
    path("farms/<int:pk>/", views.FarmDetailView.as_view(), name="farm-detail"),
    path("farms/<int:pk>/edit/", views.FarmUpdateView.as_view(), name="farm-edit"),
    path("farms/<int:pk>/delete/", views.FarmDeleteView.as_view(), name="farm-delete"),
    path("crops/", views.CropListView.as_view(), name="crop-list"),
    path("crops/add/", views.CropCreateView.as_view(), name="crop-add"),
    path("crops/<int:pk>/", views.CropDetailView.as_view(), name="crop-detail"),
    path("crops/<int:pk>/edit/", views.CropUpdateView.as_view(), name="crop-edit"),
    path("crops/<int:pk>/delete/", views.CropDeleteView.as_view(), name="crop-delete"),
    path("activities/", views.ActivityListView.as_view(), name="activity-list"),
    path("activities/add/", views.ActivityCreateView.as_view(), name="activity-add"),
    path("activities/<int:pk>/", views.ActivityDetailView.as_view(), name="activity-detail"),
    path("activities/<int:pk>/edit/", views.ActivityUpdateView.as_view(), name="activity-edit"),
    path("activities/<int:pk>/delete/", views.ActivityDeleteView.as_view(), name="activity-delete"),
    path("expenses/", views.ExpenseListView.as_view(), name="expense-list"),
    path("expenses/add/", views.ExpenseCreateView.as_view(), name="expense-add"),
    path("expenses/<int:pk>/", views.ExpenseDetailView.as_view(), name="expense-detail"),
    path("expenses/<int:pk>/edit/", views.ExpenseUpdateView.as_view(), name="expense-edit"),
    path("expenses/<int:pk>/delete/", views.ExpenseDeleteView.as_view(), name="expense-delete"),
    path("harvests/", views.HarvestListView.as_view(), name="harvest-list"),
    path("harvests/add/", views.HarvestCreateView.as_view(), name="harvest-add"),
    path("harvests/<int:pk>/", views.HarvestDetailView.as_view(), name="harvest-detail"),
    path("harvests/<int:pk>/edit/", views.HarvestUpdateView.as_view(), name="harvest-edit"),
    path("harvests/<int:pk>/delete/", views.HarvestDeleteView.as_view(), name="harvest-delete"),
]
