# Generated for the Agriculture Process Management System academic project.
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("farm_name", models.CharField(max_length=120)),
                ("owner_name", models.CharField(max_length=120)),
                ("registration_number", models.CharField(blank=True, max_length=60)),
                ("farm_type", models.CharField(choices=[("organic", "Organic"), ("traditional", "Traditional"), ("mixed", "Mixed"), ("greenhouse", "Greenhouse")], default="mixed", max_length=20)),
                ("address", models.TextField()),
                ("district", models.CharField(max_length=80)),
                ("state", models.CharField(max_length=80)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("measurement_unit", models.CharField(default="acre", max_length=20)),
                ("length", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("width", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("total_area", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("soil_type", models.CharField(max_length=80)),
                ("soil_test_result", models.TextField(blank=True)),
                ("irrigation_type", models.CharField(max_length=80)),
                ("water_source", models.CharField(max_length=80)),
                ("water_availability", models.CharField(max_length=80)),
                ("irrigation_schedule", models.CharField(blank=True, max_length=120)),
                ("water_usage", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="farms", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["farm_name"]},
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("crop_registration_number", models.CharField(max_length=60)),
                ("crop_code", models.CharField(max_length=30)),
                ("crop_name", models.CharField(max_length=100)),
                ("crop_variety", models.CharField(max_length=100)),
                ("crop_category", models.CharField(max_length=80)),
                ("season", models.CharField(choices=[("kharif", "Kharif"), ("rabi", "Rabi"), ("zaid", "Zaid"), ("annual", "Annual")], max_length=20)),
                ("sowing_date", models.DateField()),
                ("sowing_method", models.CharField(max_length=80)),
                ("seed_spacing", models.CharField(blank=True, max_length=80)),
                ("crop_status", models.CharField(choices=[("planned", "Planned"), ("sown", "Sown"), ("growing", "Growing"), ("ready", "Ready for Harvest"), ("harvested", "Harvested"), ("cancelled", "Cancelled")], default="planned", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("farm", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crops", to="farmops.farm")),
            ],
            options={"ordering": ["-sowing_date", "crop_name"]},
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity_name", models.CharField(max_length=120)),
                ("activity_type", models.CharField(choices=[("sowing", "Sowing"), ("irrigation", "Irrigation"), ("fertilization", "Fertilization"), ("pest_control", "Pest Control"), ("spraying", "Pesticide Spraying"), ("weeding", "Weeding"), ("other", "Other")], max_length=30)),
                ("activity_date", models.DateField()),
                ("performed_date", models.DateField(blank=True, null=True)),
                ("activity_status", models.CharField(choices=[("planned", "Planned"), ("in_progress", "In Progress"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="planned", max_length=20)),
                ("remarks", models.TextField(blank=True)),
                ("crop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="farmops.crop")),
            ],
            options={"ordering": ["activity_date"]},
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expense_date", models.DateField()),
                ("expense_period", models.CharField(blank=True, max_length=80)),
                ("expense_category", models.CharField(choices=[("seed", "Seed"), ("fertilizer", "Fertilizer"), ("pesticide", "Pesticide"), ("labour", "Labour"), ("machinery", "Machinery"), ("irrigation", "Irrigation"), ("transport", "Transportation"), ("other", "Other")], max_length=30)),
                ("quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("labour_details", models.CharField(blank=True, max_length=160)),
                ("machinery_usage_duration", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("rental_or_maintenance_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("water_usage_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("distance_charges", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("payment_details", models.CharField(choices=[("cash", "Cash"), ("upi", "UPI"), ("bank", "Bank"), ("credit", "Credit")], default="cash", max_length=20)),
                ("total_expense_amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("notes", models.TextField(blank=True)),
                ("crop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="farmops.crop")),
            ],
            options={"ordering": ["-expense_date"]},
        ),
        migrations.CreateModel(
            name="Harvest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("harvest_date", models.DateField()),
                ("harvest_start_date", models.DateField()),
                ("harvest_end_date", models.DateField()),
                ("harvest_season", models.CharField(max_length=40)),
                ("harvested_quantity", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("unit_of_measurement", models.CharField(default="kg", max_length=20)),
                ("expected_yield", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("actual_yield", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("yield_quality", models.CharField(choices=[("excellent", "Excellent"), ("good", "Good"), ("average", "Average"), ("poor", "Poor")], default="good", max_length=20)),
                ("storage_location", models.CharField(blank=True, max_length=160)),
                ("storage_quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("storage_type", models.CharField(blank=True, max_length=80)),
                ("storage_date", models.DateField(blank=True, null=True)),
                ("is_sold", models.BooleanField(default=False)),
                ("selling_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_income", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("buyer_details", models.CharField(blank=True, max_length=160)),
                ("selling_date", models.DateField(blank=True, null=True)),
                ("crop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="harvests", to="farmops.crop")),
            ],
            options={"ordering": ["-harvest_date"]},
        ),
        migrations.AddConstraint(model_name="farm", constraint=models.UniqueConstraint(fields=("owner", "farm_name"), name="unique_farm_name_per_owner")),
        migrations.AddConstraint(model_name="crop", constraint=models.UniqueConstraint(fields=("farm", "crop_code"), name="unique_crop_code_per_farm")),
    ]
